// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7WnY_BT_rw47hbl0Bl0h-DdZqrTL799E',
    appId: '1:377736655306:web:b7eadc0088144b6aa89f33',
    messagingSenderId: '377736655306',
    projectId: 'invox-93ca0',
    authDomain: 'invox-93ca0.firebaseapp.com',
    storageBucket: 'invox-93ca0.appspot.com',
    measurementId: 'G-HN2DJEL917',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnzPvIQ6E6SbPR_MnQ5RS3-BBu3BAc6Cs',
    appId: '1:377736655306:android:3aea4b2556ad7d0ba89f33',
    messagingSenderId: '377736655306',
    projectId: 'invox-93ca0',
    storageBucket: 'invox-93ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4m8TnebWAs0vAAewYAx023E_qYpoADI4',
    appId: '1:377736655306:ios:2ffea916401575b0a89f33',
    messagingSenderId: '377736655306',
    projectId: 'invox-93ca0',
    storageBucket: 'invox-93ca0.appspot.com',
    iosClientId:
        '377736655306-72nagta1eacsbs25auqfepp1pe9o91il.apps.googleusercontent.com',
    iosBundleId: 'com.example.invox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4m8TnebWAs0vAAewYAx023E_qYpoADI4',
    appId: '1:377736655306:ios:2ffea916401575b0a89f33',
    messagingSenderId: '377736655306',
    projectId: 'invox-93ca0',
    storageBucket: 'invox-93ca0.appspot.com',
    iosClientId:
        '377736655306-72nagta1eacsbs25auqfepp1pe9o91il.apps.googleusercontent.com',
    iosBundleId: 'com.example.invox',
  );
}
